version: "3.8"
services:           
    app:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: wspersons
        restart: unless-stopped
        ports: 
            - 3000:3000


